version: '3.4'

services:
  chat.api:
    image: ${DOCKER_REGISTRY-}chat-api
    build:
      context: .
      dockerfile: Chat.Api/Dockerfile

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"



